### ISSUE TITLE
Use Postgres instead of MS SQL

### ISSUE THREAD

**Issue by abitrolly** [epam/OSCI#2]
Please, guys, don't be cynical. 

https://github.com/epam/OSCI/blob/67443b6c4e8289d327fc05fec902f141a581e628/dbconnector.py#L30

**Comment by patrickstephens1** [comment]
Hi Anatoli,
I totally agree with your comment using a proprietry DB in the context of an open source project.  The simple reason it uses SQL Server is because that was the one the original developer was most familiar with.   Ideally it would be DB neutral.  We have in our backlog a task to move to an open source database.  If you have any time and interest to work with us, let me know!

**Comment by abitrolly** [comment]
@patrickstephens1 hi, Patrick. I have a plenty of time on my hands to help with this shortage of manpower.

**Comment by patrickstephens1** [comment]
Great. Let's do it!

**Comment by patrickstephens1** [comment]
Hi Anatoli, I just want to say thanks for the inputs. Apologies if we are a little slow responding due to other priorities but we do appreciate. @EmbeddAlex will help.

**Comment by vlad-isayko** [comment]
We just migrate from MS SQL

**Comment by abitrolly** [comment]
>
> Hi Anatoli, I just want to say thanks for the inputs. Apologies if we are
> a little slow responding due to other priorities but we do appreciate.
> @EmbeddAlex <https://github.com/EmbeddAlex> will help.
>
Thanks, Patrick. Although I would appreciate a better communication about
changes that lead to closing issues.

**Comment by vlad-isayko** [comment]
Solved since MS SQL is no longer used after commit https://github.com/epam/OSCI/commit/2641af39d8b22aca069a31cee66948bf84f3f4b4
