### ISSUE TITLE
Active contributor : query

### ISSUE THREAD

**Issue by vvijayalakshmi21** [epam/OSCI#59]
Hi,
Say if developer X makes 10 commits in Jan 2021 and does another 10 in the next month i.e. Feb 2021 and there is developer Y who makes 10 commits in the month of Feb 2021 only.

Does the active contributor number for the organization show 2 or 3?

I assume it is 2. 
Please can someone help confirm.

**Comment by vlad-isayko** [comment]
Hi, you're right. There will be 2.

If you have any more questions, you can reopen this issue or create a new one.

**Comment by vvijayalakshmi21** [comment]
Thanks.
Need clarification on a couple more scenarios.
1) If developer A didn't make any commits in the month of Feb, would the monthly active contributors still be 2?
2) If developer A made commits in December 2020 and didn't do any in the month of Jan 2021, what would be the monthly active contributor figure for Jan 2021? & the total community figure for that organization?

**Comment by vlad-isayko** [comment]
1. Since developer A has already made 10 commits, he is already an active contributor. And at the end of February, there will be two active ones.
2. Since our ratings are calculated from the beginning of the year, then the date (Year-To-Date), then the activities of previous years are not taken into account. And the total number of the community is the number of people who have made at least one commit since the beginning of the year.
