### ISSUE TITLE
Decouple MS SQL queries from local filesystem

### ISSUE THREAD

**Issue by abitrolly** [epam/OSCI#9]
OSCI software uses MS SQL specific instructions to load data from a file on a local filesystem. The error is easily repeatable when using MS SQL on different hosts or in CI/CD container - https://travis-ci.com/epam/OSCI/builds/148387944#L369

```
[SQL Server]Cannot bulk load. The file "/home/travis/build/epam/OSCI/resources/2019-01-01-9-formatted.json" does not exist or you don\'t have file access rights. (4860)
```

Blocker for porting code to an open source database (#2) and for integration tests. 

https://github.com/epam/OSCI/blob/b42ee5100a6ddfcd1ed57462de5bad90322e33aa/.travis.yml#L24

**Comment by abitrolly** [comment]
@patrickstephens1 do you know anyone with Python3 + MS SQL skills to rewrite the data loading from local file to JSON data fed from Python over net (and ideally measure the drop of performance)?

**Comment by abitrolly** [comment]
@patrickstephens1 could you find a person with T-SQL + Python skills in your organization to help port this part of code?

**Comment by abitrolly** [comment]
I updated the issue title and description for clarity.

**Comment by abitrolly** [comment]
@patrickstephens1 friendly ping.

**Comment by patrickstephens1** [comment]
Hi Anatoli, we have work in progress to move away from MS SQL entirely, although it's being done on our own internal infrastructure for some logistic reasons, we will be moving it here onto GitHub quite soon. We have in our near plan to follow-up on your comments - not being ignored!

**Comment by abitrolly** [comment]
Not really an open source way of doing things, but thanks for the heads up anyway. :D

**Comment by patrickstephens1** [comment]
Understood, we aim to change this way of working.

**Comment by abitrolly** [comment]
@patrickstephens1 come join https://sustainoss.org/ - there are working groups that try to define principles that can be adopted by corporations who want to establish a viable open source culture.

**Comment by vlad-isayko** [comment]
Solved since MS SQL is no longer used

**Comment by abitrolly** [comment]
@vlad-isayko care to mention the commit?

**Comment by vlad-isayko** [comment]
Solved since MS SQL is no longer used after commit https://github.com/epam/OSCI/commit/2641af39d8b22aca069a31cee66948bf84f3f4b4

**Comment by abitrolly** [comment]
Am I right that now it depends on Azure service that is not possible to run on premise?

**Comment by vlad-isayko** [comment]
Hi, @abitrolly 

Indeed, we use Azure Cloud for our needs. However, the project is designed so that there is no need for Azure services. In order to repeat our results, you can use completely standard computer resources (it is enough to have an operating system with python and install the required dependencies from requirements.txt https://github.com/epam/OSCI#installation). The only thing that is better to use Linux, this is how Apache Spark is used, which works better on Linux, although all should work for other OS as well.

To start, just use the CLI examples are described here https://github.com/epam/OSCI#sample-run

If you have any questions about the new architecture, feel free to ask. You can contact me here or personally by email specified in the profile.

**Comment by abitrolly** [comment]
@vlad-isayko thanks! I will try it.

**Comment by abitrolly** [comment]
No. I won't try. Too late. (
